### ISSUE TITLE
Provide sidebar mode

### ISSUE THREAD

**Issue by LuRenJiasWorld** [smartwebassistant/chrome_extension#1]
Hi, your extension is surprisingly simple but useful, and it would be better if it has a bigger UI like display in sidebar.

Could you consider implementing this? Thank you!

**Comment by smartwebassistant** [comment]
hey, glad you like it. let me research that

**Comment by smartwebassistant** [comment]
Please check the latest master @LuRenJiasWorld , a new toggle button is added on top of the popup so that you can switch to sidepanel mode. let me know if it works well or not.
